modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="naming"
version="${file.jarVersion}"
displayName="Naming"
authors="SkySom, Divine"
description='''The Namer's Art'''

[[dependencies.naming]]
modId="forge"
mandatory=true #mandatory
versionRange="[40.1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.naming]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"